-- One explicit mutable state record shared by the narrowly owned runtime modules.

local State = {}

function State.New()
    return {
        retained = {},
        built = false,
        visible = false,
        hide_reason = "startup",
        world_ready = false,
        world_quarantined = true,
        -- nil means the native game has not answered yet. Unknown deliberately
        -- fails open so observer availability cannot remove the overworld map.
        area_map_available = nil,
        area_map_reason = "unobserved",
        area_map_source = "unobserved",
        area_map_area_id = nil,
        area_map_pan_x = nil,
        area_map_pan_y = nil,
        area_map_world_x = nil,
        area_map_world_y = nil,
        area_map_world_z = nil,
        area_map_bounds_inside = nil,
        area_map_bounds_crossings = 0,
        area_map_last_crossing = "unobserved",
        area_map_exact_value = nil,
        area_map_exact_reason = "unobserved",
        area_map_diag_sequence = 0,
        lifecycle_epoch = 0,
        scheduler_generation = 0,
        step_count = 0,
        visible_step_count = 0,
        pan_update_phase = 0,
        arrow_update_phase = 0,
        pose_delay_remainder = 0.0,
        build_retry_countdown = 0,
        -- v0.18.39: consecutive failed Renderer.Build() attempts, driving the backoff
        -- ladder in Runtime/Lifecycle.lua. Reset by teardown and by world release.
        build_retry_failures = 0,
        player = nil,
        controller = nil,
        camera_manager = nil,
        camera_yaw = nil,
        camera_heading_source = "unavailable",
        camera_heading_error_logged = false,
        player_yaw = nil,
        map_rotation_angle = 0.0,
        last_map_rotation_angle = nil,
        overlay_refresh_requested = true,
        local_overlay_refresh_requested = true,
        pan_position_value = { X = 0.5, Y = 0.5 },
        player_world_x = nil,
        player_world_y = nil,
        player_world_z = nil,
        map_center_world_x = nil,
        map_center_world_y = nil,
        last_pan_x = nil,
        last_pan_y = nil,
        last_yaw = nil,
        pose_error_streak = 0,
        pose_error_logged = false,
        engine_write_error_logged = false,
        last_error = nil,
        last_build_status = nil,
        widget_counter = 0,
        rebuild_requested = false,
        -- v0.18.40: the debounce that turns a run of rebuild-flagged setting steps into one
        -- rebuild. nil means nothing is pending. See Runtime/Lifecycle.lua.
        rebuild_deadline = nil,
        rebuild_coalesced = 0,
        modui = nil,
        modui_client = nil,
        modui_available = false,
        modui_hotkey_enabled = false,
        modui_shell_active = false,
        native_menu_gate_available = false,
        native_menu_active = false,
        native_menu_state = "unavailable",
        native_menu_sequence = 0,
        settings_open = false,
        settings_closing = false,
        settings_generation = 0,
        active_generation = 0,
        settings_tab = 1,
        settings_selected_by_tab = { 1, 1, 1, 1, 1, 1 },
        settings_selection = 1,
        settings_reset_pending_tab = 0,
        bind_capture = { active = false },
        bind_capture_status = "",
        modui_native_request_sequence = 0,
        modui_native_event_sequence = 0,
        modui_native_host_epoch = "",
        modui_ownership_mismatch_steps = 0,
        native_pause_component = nil,
        native_pause_bumped = false,
        native_pause_bumps = 0,
        native_pause_reason = nil,
        native_modal_pending_cleanup = nil,
        native_modal_handler = nil,
        native_modal_asc = nil,
        native_modal_handles = {},
        native_modal_isolation = false,
        native_modal_mode = "none",
        native_menu_block_verified = false,
        native_modal_pre_map_allowed = nil,
        native_modal_pre_options_allowed = nil,
        last_action = "",
        last_action_step = -100,
        load_map_pre_ready = false,
        poi = nil,
        performance = {
            pose_calls = 0,
            pose_successes = 0,
            pan_due = 0,
            arrow_due = 0,
            pan_writes = 0,
            pan_skips = 0,
            rotation_writes = 0,
            rotation_skips = 0,
            arrow_writes = 0,
            arrow_skips = 0,
            map_geometry_changes = 0,
            overlay_update_runs = 0,
            overlay_update_skips = 0,
            projection_context_updates = 0,
            modui_action_reads = 0,
            modui_empty_action_reads = 0,
            modui_actions_received = 0,
            modui_shell_reads = 0,
            modui_visibility_snapshots = 0,
            modui_full_metadata_reads = 0,
            modui_visibility_fallbacks = 0,
        },
    }
end

return State
