-- MortalShell2TTS Config.Codec
-- Pure complete-snapshot validation and deterministic INI serialization.
-- File IO, backup/recovery, migration, sanitation and runtime persistence remain
-- owned by MortalShell2TTS main.lua.

local Codec = {}

local function trim(value)
    return (tostring(value or ""):gsub("^%s+", ""):gsub("%s+$", ""))
end

function Codec.SnapshotValid(content)
    content = tostring(content or "")
    if content == "" or #content > 1024 * 1024 then return false, "empty-or-oversized" end

    local schema = 1
    local sections = { mod = false, speech = false, engine = false }
    local last_nonempty = ""
    for raw_line in content:gmatch("[^\r\n]+") do
        local line = trim(raw_line)
        if line ~= "" then
            last_nonempty = line
            local schema_value = line:match("^[Cc]onfig[Ss]chema%s*=%s*(%d+)%s*$")
            if schema_value ~= nil then schema = math.max(1, tonumber(schema_value) or 1) end
            local lower = line:lower()
            if lower == "[mod]" then sections.mod = true end
            if lower == "[speech]" then sections.speech = true end
            if lower == "[engine]" then sections.engine = true end
        end
    end

    if schema >= 3 then
        if last_nonempty ~= "; MortalShell2TTSConfigEnd=1" then return false, "missing-or-nonfinal-end-marker" end
        if not sections.mod or not sections.speech or not sections.engine then return false, "missing-required-section" end
    end
    return true, nil
end

function Codec.Serialize(config, schema, voice_profiles, queue_behavior, duplicate_seconds)
    config = type(config) == "table" and config or {}
    return table.concat({
        "; MortalShell2TTS settings - generated by the in-game menu",
        "; This file is intentionally not shipped in release archives so updates do not overwrite user settings.",
        "",
        "[Meta]",
        "ConfigSchema=" .. tostring(schema),
        "",
        "[Mod]",
        "Narration=" .. (config.narration and "true" or "false"),
        "ReadDelayMs=" .. tostring(config.read_delay_ms),
        "AnnouncePageNumber=" .. (config.announce_page_number and "true" or "false"),
        "MenuKeybind=" .. tostring(config.menu_keybind),
        "ControllerMenuBind=" .. tostring(config.controller_menu_bind),
        "MatchModifierSides=" .. (config.modifier_sides_equivalent and "true" or "false"),
        "PauseGameWhileMenuOpen=" .. (config.pause_game_while_menu_open and "true" or "false"),
        "LogPerformance=" .. (config.log_performance and "true" or "false"),
        "DebugLogging=" .. (config.debug_logging and "true" or "false"),
        "PanelOpacity=" .. tostring(config.panel_opacity),
        "PanelFontSize=" .. tostring(config.panel_font_size),
        "",
        "[Speech]",
        "Voice=" .. tostring(config.voice),
        "AzureVoice=" .. tostring(config.azure_voice),
        "Rate=" .. tostring(config.rate),
        "Volume=" .. tostring(config.volume),
        "Pitch=" .. tostring(config.pitch),
        "VoiceStyle=" .. tostring(config.voice_style),
        "FavoriteWindowsVoices=" .. tostring(config.favorite_windows_voices),
        "FavoriteAzureVoices=" .. tostring(config.favorite_azure_voices),
        "SpeechQueue=" .. tostring(queue_behavior),
        "DuplicateTextSeconds=" .. tostring(duplicate_seconds),
        "PronunciationCorrections=" .. (config.pronunciation_corrections ~= false and "true" or "false"),
        "VoiceProfiles=" .. tostring(voice_profiles),
        "",
        "[Engine]",
        "Engine=" .. tostring(config.engine),
        "AudioOutput=" .. tostring(config.audio_output),
        "AzureRegion=" .. tostring(config.azure_region),
        "",
        "; MortalShell2TTSConfigEnd=1",
        "",
    }, "\r\n")
end

return Codec
